### ISSUE TITLE
Could you make a video or explanation on how to use this? Because I’m not understanding how exactly it works.

### ISSUE THREAD

**Issue by Oh-Turry** [intezer/analyze-python-sdk#23]
If not please help with this error, I've used your example for send_file_file()

```

File "c:\Users\Turry\Turry's Cloud\test_lounge\python\test.py", line 26
    send_file_with_wait("C:\Users\Turry\Documents\Optimizations\ImproveConnection.reg")
                                                                                      ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

```

**Comment by davidt99** [comment]
Looks like you didn't escape the backslashes, you can add `r` before the path.

**Comment by Oh-Turry** [comment]
> Looks like you didn't escape the backslashes, you can add `r` before the path.

Yeah but it still doesn't work

**Comment by davidt99** [comment]
Can you share the new error and the code?
Also, did you see the examples [directory](https://github.com/intezer/analyze-python-sdk/tree/master/examples) we have?

**Comment by Oh-Turry** [comment]
```
Traceback (most recent call last):
  File "c:\Users\Turry\Turry's Cloud\test_lounge\python\test.py", line 24, in <module>
    send_file_with_wait(*sys.argv[1:])
TypeError: send_file_with_wait() missing 1 required positional argument: 'file_path'
```

**Comment by Oh-Turry** [comment]
I added the in my code at the beginning

**Comment by davidt99** [comment]
You posted the output, not the code.
if you want to analyze a file on your computer, try maybe this snippet:
```
from intezer_sdk import api
from intezer_sdk.analysis import Analysis

api.set_global_api('<api_key>')
analysis = Analysis(file_path=r'C:\Users\Turry\Documents\Optimizations\ImproveConnection.reg')
analysis.send(wait=True)
pprint(analysis.result())
```

**Comment by davidt99** [comment]
I'm closing this issue for now, let me know if you have more issue.
